

mailjet 

5b98441686a0e79036bd937a831f0e75 api 

5782a5e1f50af5cc509588e1c5c13d40  secret


CREATE TABLE entities (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    Entity TEXT NOT NULL,
    EntityID   TEXT NOT NULL,
    EntityProjectDetails TEXT NOT NULL,
   
  
);

-- Table: indicator_reports
CREATE TABLE indicator_reports (
   id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    RID   TEXT NOT NULL,
    IID TEXT NOT NULL,
    EntityID TEXT NOT NULL,
    ReportingID TEXT NOT NULL,
    ReportedBy TEXT NULL,
    Response TEXT NOT NULL,
    AnsweredQuestion TEXT NOT NULL,
    Comments TEXT NOT NULL,
    IndicatorScore TEXT  NULL,
    ApprovalStatus TEXT NOT NULL DEFAULT 'false',
    ResponseType TEXT DEFAULT NULL,
   
);

-- Table: project_indicators
CREATE TABLE project_indicators (
   id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    IndicatorPrimaryCategory TEXT DEFAULT NULL,
    IndicatorSecondaryCategory TEXT DEFAULT NULL,
    EntityID TEXT NOT NULL,
    IID   TEXT NOT NULL,
    Indicator TEXT DEFAULT NULL,
    IndicatorDefinition TEXT NOT NULL,
    IndicatorQuestion TEXT NOT NULL,
    RemarksComments TEXT DEFAULT NULL,
    SourceOfData TEXT DEFAULT NULL,
    ResponseType TEXT NOT NULL,
    ReportingPeriod TEXT DEFAULT NULL,
   
   
);

-- Table: reporting_timelines
CREATE TABLE reporting_timelines (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    ReportName TEXT NOT NULL,
    Type TEXT NOT NULL,
    Description TEXT NOT NULL,
    ReportingID   TEXT NOT NULL,
    Year INT NOT NULL,
   
    status TEXT DEFAULT 'active',
  
);

-- Table: users
CREATE TABLE musers (
   id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    name TEXT NOT NULL,
    EntityID TEXT DEFAULT NULL,
    UserCode TEXT DEFAULT NULL,
    Phone TEXT DEFAULT NULL,
    Nationality TEXT DEFAULT NULL,
    PhoneNumber TEXT DEFAULT NULL,
    Address TEXT DEFAULT NULL,
    ParentOrganization TEXT DEFAULT NULL,
    Sex TEXT DEFAULT NULL,
    JobTitle TEXT DEFAULT NULL,
    AccountRole TEXT DEFAULT NULL,
    UserID   TEXT NOT NULL,
  
    password TEXT DEFAULT NULL,
  
    PRIMARY KEY (id)
);


-- views  project_indicators_with_entities
CREATE VIEW project_indicators_with_entities AS
SELECT 
    pi.id,
    pi.indicatorprimarycategory,
    pi.indicatorsecondarycategory,
    pi.entityid,
    pi.iid,
    pi.indicator,
    pi.indicatordefinition,
    pi.indicatorquestion,
    pi.remarkscomments,
    pi.sourceofdata,
    pi.responsetype,
    pi.reportingperiod,
    pi.created_at,
    pi.updated_at,
    e.entity
FROM 
    project_indicators pi
JOIN 
    entities e ON pi.entityid = e.entityid;
-- views


-- reports insert

-- Enable the uuid-ossp extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO reporting_timelines (
    reportname, 
    type, 
    description, 
    reportingid, 
    year, 
    created_at, 
    updated_at, 
    status
) VALUES
    ('Annual Report 2024', 'Annual Report', 'Annual Report 2024', 'f78f0f80-48df-67e6-1b61-4f2d3eefa771', 2024, NULL, NULL, 'Active'),
    ('Bi - Annual Report 2024 (July)', 'Bi-Annual Report', 'Bi - Annual Report 2024 (July)', '442f379c-28c3-a47c-4c2e-f6cb45796286', 2024, NULL, NULL, 'Active'),
    ('Bi - Annual Report 2024 (December)', 'Quarterly Report', 'Bi - Annual Report 2024 (December)', '2f84dd24-7aa1-6b7f-4130-052b0eec1867', 2024, NULL, NULL, 'active'),
    ('Quarter 1 report 2024', 'Quarterly Report', 'Quarter 1 report 2024', '5bc6cbf7-67c9-24ad-0511-d24e58023b1f', 2024, NULL, NULL, 'active'),
    ('Quarter 2 report 2024', 'Quarterly Report', 'Quarter 2 report 2024', '0c8195f1-6947-4930-8239-34cb488b6b7c', 2024, NULL, NULL, 'active'),
    ('Quarter 3 report 2024', 'Quarterly Report', 'Quarter 3 report 2024', 'df86fb09-ee39-0f85-2d49-08d0122e953a', 2024, NULL, NULL, 'active'),
    ('Quarter 4 report 2024', 'Quarterly Report', 'Quarter 4 report 2024', '99c37be6-6edf-6de5-3cb5-1066fb83ce43', 2024, NULL, NULL, 'active');

-- reports insert



-- indicator insert

-- Assuming uuid-ossp extension is already enabled in the database
-- If not, you need to enable it with:
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO project_indicators (
    indicatorprimarycategory, 
    indicatorsecondarycategory, 
    entityid, 
    indicator, 
    indicatordefinition, 
    indicatorquestion, 
    remarkscomments, 
    sourceofdata, 
    responsetype, 
    reportingperiod, 
    created_at, 
    updated_at
) VALUES
    ('Regional Results Framework', 'Country Specific Intermediate Results Indicators', 'cf647582323c0f9a767a3149cfda960f', 'sss', 'ss9999999999', 'AccountRoleAccountRole', 'AccountRole', NULL, 'Text', 'Bi-Annual Report', NULL, NULL),
    ('Country Results Framework', 'Country Specific Intermediate Results Indicators', 'cf647582323c0f9a767a3149cfda960f', 'dkldkldkl', 'ss9999999999', 'hgghgg', 'jjhjhjjh', NULL, 'Percentage', 'Bi-Annual Report', NULL, NULL),
    ('Country Results Framework', 'Country Specific Intermediate Results Indicators', 'cf647582323c0f9a767a3149cfda960f', 'dkldkldkl', 'dkldkldkl', 'dkldkldkl', 'dkldkldkl', NULL, 'Percentage', 'Bi-Annual Report', NULL, NULL);

-- indicator insert


-- entities insert
-- Enable the uuid-ossp extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO entities (
    entity, 
    entityid, 
    entityprojectdetails, 
    created_at, 
    updated_at
) VALUES
    ('Ethiopia', 'fdb7f1f1cf5742d85b34d5bdf2e5e3c0', 'MPA ENTITY', '2024-07-03 05:34:08', '2024-07-03 05:34:08'),
    ('STP', '94a8a9c32a22811040c5eafadeb698fe', 'MPA ENTITY', '2024-07-03 10:03:28', '2024-07-03 10:03:28'),
    ('DRC', 'cf647582323c0f9a767a3149cfda960f', 'MPA ENTITY', '2024-07-03 10:04:31', '2024-07-03 10:04:31'),
    ('Rwanda', '26bc6cd17ef8f6d206f10eefd507fc3e', 'MPA ENTITY', '2024-07-03 10:04:50', '2024-07-03 10:04:50'),
    ('Burundi', '4eac152325738352f51e16046d3dbe7f', 'MPA ENTITY', '2024-07-03 10:05:30', '2024-07-03 10:05:30'),
    ('ECSA-HC', 'ac7eaa6a06a1b0e19eb41e5dbe224d58', 'MPA ENTITY', '2024-07-03 10:06:37', '2024-07-03 10:06:37'),
    ('IGAD', '7848dc358943f0c74dfe6a00f00fc8e1', 'MPA ENTITY', '2024-07-03 10:06:56', '2024-07-03 10:06:56'),
    ('Kenya', 'da1dbd6dadb88a7c3065bfc3df4f9edb', 'MPA ENTITY', '2024-07-03 10:07:29', '2024-07-03 10:07:29'),
    
-- entities insert

-- grant all to anon 

GRANT USAGE ON SCHEMA mpa TO anon;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA mpa TO anon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA mpa TO anon;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA mpa TO anon;

-- grant all to anon 



-- Reporting Views
CREATE VIEW indicator_reports_view AS

SELECT
    ir.RID,
    ir.IID,
    ir.EntityID,
    ir.ReportingID,
    ir.ReportedBy,
    ir.Response,
    ir.Comments,
    ir.IndicatorScore,
    ir.ApprovalStatus,
    ir.ResponseType AS indicator_report_response_type,
    e.Entity,
    e.EntityProjectDetails,
    pi.IndicatorPrimaryCategory,
    pi.IndicatorSecondaryCategory,
    pi.Indicator,
    pi.IndicatorDefinition,
    pi.IndicatorQuestion,
    pi.RemarksComments,
    pi.SourceOfData,
    pi.ResponseType AS project_indicator_response_type,
    pi.ReportingPeriod,
    rt.ReportName,
    rt.Type AS report_type,
    rt.Description,
    rt.Year
  
FROM
    indicator_reports ir
INNER JOIN entities e ON ir.EntityID = e.EntityID
INNER JOIN project_indicators pi ON ir.IID = pi.IID 
INNER JOIN reporting_timelines rt ON ir.ReportingID = rt.ReportingID


-- Reporting Views


-- mpa_active_indicator_reports_details
SELECT DISTINCT
    ir.id,
    ir.RID,
    ir.IID,
    ir.EntityID,
    ir.ReportingID,
    ir.ReportedBy,
    ir.Response,
    ir.Comments,
    ir.IndicatorScore,
    ir.ApprovalStatus,
    ir.ResponseType,
    e.Entity,
    pi.IndicatorPrimaryCategory,
    pi.IndicatorSecondaryCategory,
    pi.Indicator,
    pi.IndicatorDefinition,
    pi.IndicatorQuestion,
    pi.RemarksComments,
    pi.SourceOfData,
    pi.ReportingPeriod,
    rt.ReportName,
    rt.Type,
    rt.Description,
    rt.Year,
    rt.status
FROM
    mpa_indicator_reports ir
JOIN
    mpa_entities e ON ir.EntityID = e.EntityID
JOIN
    mpa_project_indicators pi ON ir.IID = pi.IID
JOIN
    mpa_reporting_timelines rt ON ir.ReportingID = rt.ReportingID
WHERE
    rt.status = 'active';

-- mpa_active_indicator_reports_details



-- mpa_project_indicators_with_entities
SELECT 
    pi.id,
    pi.IndicatorPrimaryCategory,
    pi.IndicatorSecondaryCategory,
    pi.EntityID,
    pi.IID,
    pi.Indicator,
    pi.IndicatorDefinition,
    pi.IndicatorQuestion,
    pi.RemarksComments,
    pi.SourceOfData,
    pi.ResponseType,
    pi.ReportingPeriod,   
    e.Entity
FROM 
    mpa_project_indicators pi
JOIN 
    mpa_entities e ON pi.EntityID = e.EntityID;
-- mpa_project_indicators_with_entities

-- mpa_reported_indicators_detailed_view

SELECT DISTINCT
    ir.id,
    ir.RID,
    ir.IID,
    ir.EntityID,
    ir.ReportingID,
    ir.ReportedBy,
    ir.Response,
    ir.Comments,
    ir.IndicatorScore,
    ir.ApprovalStatus,
    ir.ResponseType,
    e.Entity,
    pi.IndicatorPrimaryCategory,
    pi.IndicatorSecondaryCategory,
    pi.Indicator,
    pi.IndicatorDefinition,
    pi.IndicatorQuestion,
    pi.RemarksComments,
    pi.SourceOfData,
    pi.ReportingPeriod,
    rt.ReportName,
    rt.Type,
    rt.Description,
    rt.Year,
    rt.status
FROM
    mpa_indicator_reports ir
JOIN
    mpa_entities e ON ir.EntityID = e.EntityID
JOIN
    mpa_project_indicators pi ON ir.IID = pi.IID
JOIN
    mpa_reporting_timelines rt ON ir.ReportingID = rt.ReportingID;

-- mpa_reported_indicators_detailed_view

-- mpa_rrf_active_reports

SELECT
    rt.id,
    rt.ReportName,
    rt.Type,
    rt.Description,
    rt.ReportingID,
    rt.Year
FROM
    mpa_reporting_timelines rt
INNER JOIN
    mpa_project_indicators pi ON rt.Type = pi.ReportingPeriod
WHERE
    rt.status = 'active'
    AND pi.IndicatorPrimaryCategory = 'Regional Results Framework'
GROUP BY
    rt.ReportingID;

-- mpa_rrf_indicators

SELECT DISTINCT 
    pi.id,
    pi.IndicatorPrimaryCategory,
    pi.IndicatorSecondaryCategory,
    pi.IID,
    pi.Indicator,
    pi.IndicatorDefinition,
    pi.IndicatorQuestion,
    pi.RemarksComments,
    pi.SourceOfData,
    pi.ResponseType,
    pi.ReportingPeriod,
    rt.ReportingID
FROM 
    mpa_project_indicators pi
JOIN 
    mpa_reporting_timelines rt
ON 
    pi.ReportingPeriod = rt.Type
WHERE 
    pi.IndicatorPrimaryCategory = 'Regional Results Framework';

-- mpa_rrf_indicators